### ISSUE TITLE
can you create and upload offline wwise installer somewhere?

### ISSUE THREAD

**Issue by K0shachiyamyatA** [Zhincore/cp2077-voiceswap#2]
the CDN service wwise uses seems to block any russian IPs and i don't know any free PC VPN clients that would work in Russia :(
i managed to download the launcher through tor, but the installation within launcher itself fails too.

**Comment by Zhincore** [comment]
Hi, here you go: <https://static.zhincore.eu/tmp/Wwise%202019.2.15.7667.zip>
I hope it's fine

**Comment by K0shachiyamyatA** [comment]
thx
