### ISSUE TITLE
is this normal? xd

### ISSUE THREAD

**Issue by K0shachiyamyatA** [Zhincore/cp2077-voiceswap#3]
![WindowsTerminal_VgeZf0ZAXT](https://github.com/Zhincore/cp2077-voiceswap/assets/88767403/afeb6ef6-7db6-4e9d-9124-84428a9137db)

**Comment by K0shachiyamyatA** [comment]
well it seems to work

**Comment by K0shachiyamyatA** [comment]
maybe it's related to miniconda, i reinstall the venv without it now

**Comment by K0shachiyamyatA** [comment]
ok now it works

**Comment by K0shachiyamyatA** [comment]
now the second phase just stays at 0.
![WindowsTerminal_maM9s3v1K2](https://github.com/Zhincore/cp2077-voiceswap/assets/88767403/a0cfbf75-7765-488b-8e94-e714f60dd30e)
![Taskmgr_xoPNqP6G6e](https://github.com/Zhincore/cp2077-voiceswap/assets/88767403/58de32dd-1008-4174-83a5-de9028c36fe2)

**Comment by Zhincore** [comment]
That's weird, phase 1 and 2 should run at the same time... Have you tried running the command again?

**Comment by K0shachiyamyatA** [comment]
> That's weird, phase 1 and 2 should run at the same time... Have you tried running the command again?

Yes, and i tried to clean cache and do it again from the beginning.
The second phase stays at 0 with 0 activity in task manager.

**Comment by Zhincore** [comment]
There might be an issue with the AI on your setup. You can try skipping the isolation step by renaming a folder inside `.cache` from `raw` to `isolated` (I think).

**Comment by K0shachiyamyatA** [comment]
> There might be an issue with the AI on your setup. You can try skipping the isolation step by renaming a folder inside `.cache` from `raw` to `isolated` (I think).

![browser_NhQgksx4zt](https://github.com/Zhincore/cp2077-voiceswap/assets/88767403/1167568b-73aa-4e26-add3-896f3e2ce8e2)

ok i can do this manually, which model do i use?

**Comment by Zhincore** [comment]
onnx_dereverb is great for most

**Comment by K0shachiyamyatA** [comment]
> onnx_dereverb is great for most

`.cache/split/vocals`

i need the folder structure in this one, i just moved base and ep1 with their file structures, but the 4th step revoiced exactly 0 files
![explorer_r0UBXAQzKj](https://github.com/Zhincore/cp2077-voiceswap/assets/88767403/34771a15-fdca-442a-99f9-cd46ca0c3df0)
